/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_alexander1248_jposit_PositsJNI */

#ifndef _Included_ru_alexander1248_jposit_PositsJNI
#define _Included_ru_alexander1248_jposit_PositsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    set_flags
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_alexander1248_jposit_PositsJNI_set_1flags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    get_flags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_alexander1248_jposit_PositsJNI_get_1flags
  (JNIEnv *, jclass);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_alexander1248_jposit_PositsJNI_init
  (JNIEnv *, jclass);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_nar
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1nar
  (JNIEnv *, jclass);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_fromFloat
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1fromFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_fromDouble
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1fromDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_fromInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1fromInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_fromLong
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1fromLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_toFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1toFloat
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_toDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1toDouble
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_toInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1toInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_toLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1toLong
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1sub
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1mul
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1div
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_eq
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1eq
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_le
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1le
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_lt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1lt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_neg
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1neg
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_abs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1abs
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_sign
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1sign
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_round
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1round
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_sqrt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1sqrt
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_exp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1exp
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_log
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1log
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_sin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1sin
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit32_cos
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit32_1cos
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_nar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1nar
  (JNIEnv *, jclass);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_fromFloat
 * Signature: (F)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1fromFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_fromDouble
 * Signature: (D)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1fromDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_fromInt
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1fromInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_fromLong
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1fromLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_toFloat
 * Signature: (S)F
 */
JNIEXPORT jfloat JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1toFloat
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_toDouble
 * Signature: (S)D
 */
JNIEXPORT jdouble JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1toDouble
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_toInt
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1toInt
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_toLong
 * Signature: (S)J
 */
JNIEXPORT jlong JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1toLong
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_add
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1add
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_sub
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1sub
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_mul
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1mul
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_div
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1div
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_eq
 * Signature: (SS)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1eq
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_le
 * Signature: (SS)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1le
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_lt
 * Signature: (SS)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1lt
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_neg
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1neg
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_abs
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1abs
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_sign
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1sign
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_round
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1round
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_sqrt
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1sqrt
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_exp
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1exp
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_log
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1log
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_sin
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1sin
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ru_alexander1248_jposit_PositsJNI
 * Method:    posit16_cos
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_ru_alexander1248_jposit_PositsJNI_posit16_1cos
  (JNIEnv *, jclass, jshort);

#ifdef __cplusplus
}
#endif
#endif
